### ISSUE TITLE
The main issue 

### ISSUE THREAD

**Issue by Alltheyuriz** [mnkyking/RPG-Maker-MZ-PHONE-MENU#1]
The main issue of the plugin is that it when you create dialog boxes in the menu with a common event it's not centered and it's aligned to the left

**Comment by mnkyking** [comment]
Can you provide an example?

**Comment by Alltheyuriz** [comment]
![unknown](https://user-images.githubusercontent.com/104283631/164987384-3de233e0-5efa-4d3d-a928-f6a9a52289ea.png)

**Comment by Alltheyuriz** [comment]
The only thing on now is the phone plugin and I've centered it and it still stays in the same spot

**Comment by mnkyking** [comment]
Found to be an issue between this plugin and Visustella MessageCore plugin. Resolved as NonIssue
